apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.DaemonSet.name }}
  labels:
    k8s-app: {{ .Values.DaemonSet.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.DaemonSet.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.DaemonSet.name }}
    spec:
      serviceAccountName: {{ .Values.ServiceAccount.name }}
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.DaemonSet.repo }}
        imagePullPolicy: {{ .Values.DaemonSet.pullPolicy }}
        name: {{ .Values.DaemonSet.containername }}
        volumeMounts:
        - mountPath: /sync/hosts
          name: sync-hosts
        args: [bash, sync_ds.sh,]
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: interval
          value: {{ .Values.DaemonSet.syncinterval | quote }}
        - name: ING_NAMESPACE
          value: {{ .Values.DaemonSet.ING_NAMESPACE }}
        - name: SVC_NAMESPACE
          value: {{ .Values.DaemonSet.SVC_NAMESPACE }}
      volumes:
      - name: sync-hosts
        hostPath:
          path: /etc/hosts
          type: File
